apiVersion: apps/v1
kind: Deployment
metadata:
  name: edot-user-service
spec:
  selector:
    matchLabels:
      app: edot-user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: edot-user-service
    spec:
      containers:
      - name: edot-user-service
        image: dendyramdhan/edot-user-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "edot_user_service_db"
        - name: DB_PORT
          value: "5432"

---

apiVersion: v1
kind: Service
metadata:
  name: edot-user-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080 # Optional: specify a nodePort in the range allowed by your cluster
  selector:
    app: edot-user-service
